# Generated by Django 3.2.19 on 2023-05-16 10:52

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('region', models.CharField(choices=[('London', 'London'), ('Manchester', 'Manchester'), ('Bristol', 'Bristol'), ('Newcastle', 'Newcastle')], max_length=200)),
                ('status', models.CharField(choices=[('Fee-paying', 'Fee-paying'), ('State Grammar', 'State Grammar'), ('Academy', 'Academy')], max_length=200)),
                ('gender_type', models.CharField(choices=[('Co-educational', 'Co-educational'), ('Girls', 'Girls'), ('Boys', 'Boys')], max_length=200)),
                ('class_size', models.IntegerField()),
                ('avg_maths_grade', models.IntegerField()),
                ('avg_english_grade', models.IntegerField()),
                ('percentage_gcse_5', models.IntegerField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('specialisation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.school')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
