# Generated by Django 3.2.19 on 2023-05-16 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avg_english_grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='avg_maths_grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='class_size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='percentage_gcse_5',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
