# Generated by Django 3.2.19 on 2023-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230516_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avg_english_grade',
            field=models.IntegerField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='avg_maths_grade',
            field=models.IntegerField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='percentage_gcse_5',
            field=models.IntegerField(),
        ),
    ]
