# Generated by Django 3.2.19 on 2023-05-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230516_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='school',
        ),
    ]
