# Generated by Django 3.2.19 on 2023-05-17 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='school_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
