# Generated by Django 3.2.19 on 2023-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_school_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avg_gcse_english_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='avg_gcse_maths_grade',
            field=models.IntegerField(),
        ),
    ]
