# Generated by Django 3.2.19 on 2023-05-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
